export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const SET_FILE_LIST = 'SET_FILE_LIST'
export const RESET_OCR_RES = 'RESET_OCR_RES'
export const ADD_OCR_RES = 'ADD_OCR_RES'
